const translations = {
  en: {
    mainMenu: 'MAIN MENU',
    dashboard: 'Dashboard',
    pannes: 'Pannes',
    materiel: 'Matériel',
    users: 'Users',
    rapport: 'Rapport',
    logout: 'Logout',
    newPanne: 'New Panne',
    totalPannes: 'Total Pannes',
    allIncidents: 'All incidents',
    enCours: 'In Progress',
    activeIncidents: 'Active incidents',
    terminees: 'Completed',
    resolved: 'Resolved',
    difficiles: 'Difficult',
    needAttention: 'Need attention',
    recentPannes: 'Recent Pannes',
    latestIncidents: 'Latest reported incidents',
    viewAll: 'View All',
    noPannes: 'No pannes yet — add your first one!',
    id: 'ID', service: 'Service', description: 'Description',
    priority: 'Priority', status: 'Status', technicien: 'Technician',
    date: 'Date', actions: 'Actions',
    elevee: 'High', moyenne: 'Medium', faible: 'Low',
    statusEnCours: 'In Progress', statusTerminee: 'Completed', statusDifficile: 'Difficult',
    addNewPanne: 'Add New Panne', fillDetails: 'Fill in the details below',
    servicePlaceholder: 'e.g. Radiology', descriptionPlaceholder: 'Describe the issue...',
    technicienPlaceholder: 'e.g. Ahmed B.', cancel: 'Cancel', add: 'Add',
    addMateriel: 'Add Matériel', totalEquipment: 'total equipment items',
    total: 'Total', available: 'Available', unavailable: 'Unavailable',
    nom: 'Name', type: 'Type', toggle: 'Toggle', delete: 'Delete',
    addNewMateriel: 'Add New Matériel', fillEquipment: 'Fill in the equipment details',
    addUser: 'Add User', totalUsers: 'total users registered',
    admins: 'Admins', techniciens: 'Technicians', services: 'Services',
    name: 'Name', email: 'Email', role: 'Role', joined: 'Joined',
    addNewUser: 'Add New User', fillUser: 'Fill in the user details',
    fullName: 'Full Name', namePlaceholder: 'e.g. Ahmed Ben Ali',
    emailPlaceholder: 'e.g. ahmed@hospital.tn',
    rapportTitle: 'Report', resolutionRate: 'Resolution Rate',
    ofPannesResolved: 'of pannes resolved', priorityBreakdown: 'Priority Breakdown',
    topServices: 'Top Services', topTechniciens: 'Top Technicians',
    noData: 'No data yet', pannesCount: 'pannes', interventions: 'interventions',
    performanceOverview: 'System performance overview',
    declareTitle: 'Report a Panne', declareSubtitle: 'Report a technical incident to the IT team',
    submitPanne: 'Submit Report', reportAnother: 'Report Another',
    submittedTitle: 'Report Submitted!', submittedSubtitle: 'Your report has been sent to the technical team.',
    all: 'All', filterAll: 'All', active: 'Active', inactive: 'Inactive',
    systemHealth: 'System Health', criticalActive: 'critical incidents active',
    excellent: 'Excellent', fair: 'Fair', critical: 'Critical',
    activityFeed: 'Activity Timeline', activitySubtitle: 'Chronological incident history',
    noActivity: 'No activity recorded', searchPlaceholder: 'Search by service, description or technician...',
    noResults: 'No results found', tryDifferent: 'Try a different search term',
    noPannesFound: 'No pannes found', addFirstPanne: 'Add your first panne',
    noEquipment: 'No equipment yet', addFirstEquipment: 'Add your first equipment item',
    noUsers: 'No users yet', addFirstUser: 'Add your first user',
    lowImpact: 'Low impact', mediumImpact: 'Medium impact', highImpact: 'High impact',
    statusLabel: 'Status', priorityLabel: 'Priority Level',
    thisWeek: 'this week', vsLastWeek: 'vs last week',
    incidentsOpen: 'incidents open', incidentsResolved: 'resolved this week',
    needsAttention: 'needs attention',
    recentActivity: 'Recent Pannes',
    recentActivitySub: 'Last 5 pannes',
    timelineTitle: 'Activity Timeline',
    timelineSub: 'Full incident history with details',
    justNow: 'Just now', today: 'Today', yesterday: 'Yesterday',
    assignedTo: 'Assigned to', notAssigned: 'Not assigned',
  },
  fr: {
    mainMenu: 'MENU PRINCIPAL',
    dashboard: 'Tableau de Bord',
    pannes: 'Pannes',
    materiel: 'Matériel',
    users: 'Utilisateurs',
    rapport: 'Rapport',
    logout: 'Déconnexion',
    newPanne: 'Nouvelle Panne',
    totalPannes: 'Total Pannes',
    allIncidents: 'Tous les incidents',
    enCours: 'En Cours',
    activeIncidents: 'Incidents actifs',
    terminees: 'Terminées',
    resolved: 'Résolues',
    difficiles: 'Difficiles',
    needAttention: 'Nécessite attention',
    recentPannes: 'Pannes Récentes',
    latestIncidents: 'Derniers incidents signalés',
    viewAll: 'Voir Tout',
    noPannes: 'Aucune panne — ajoutez la première!',
    id: 'ID', service: 'Service', description: 'Description',
    priority: 'Priorité', status: 'Statut', technicien: 'Technicien',
    date: 'Date', actions: 'Actions',
    elevee: 'Élevée', moyenne: 'Moyenne', faible: 'Faible',
    statusEnCours: 'En cours', statusTerminee: 'Terminée', statusDifficile: 'Difficile',
    addNewPanne: 'Ajouter une Panne', fillDetails: 'Remplissez les détails ci-dessous',
    servicePlaceholder: 'ex: Radiologie', descriptionPlaceholder: 'Décrivez le problème...',
    technicienPlaceholder: 'ex: Ahmed B.', cancel: 'Annuler', add: 'Ajouter',
    addMateriel: 'Ajouter Matériel', totalEquipment: 'équipements au total',
    total: 'Total', available: 'Disponible', unavailable: 'Indisponible',
    nom: 'Nom', type: 'Type', toggle: 'Changer', delete: 'Supprimer',
    addNewMateriel: 'Ajouter un Matériel', fillEquipment: "Détails de l'équipement",
    addUser: 'Ajouter Utilisateur', totalUsers: 'utilisateurs enregistrés',
    admins: 'Admins', techniciens: 'Techniciens', services: 'Services',
    name: 'Nom', email: 'Email', role: 'Rôle', joined: 'Inscrit le',
    addNewUser: 'Ajouter un Utilisateur', fillUser: "Détails de l'utilisateur",
    fullName: 'Nom Complet', namePlaceholder: 'ex: Ahmed Ben Ali',
    emailPlaceholder: 'ex: ahmed@hospital.tn',
    rapportTitle: 'Rapport', resolutionRate: 'Taux de Résolution',
    ofPannesResolved: 'des pannes résolues', priorityBreakdown: 'Répartition par Priorité',
    topServices: 'Top Services', topTechniciens: 'Top Techniciens',
    noData: 'Aucune donnée', pannesCount: 'pannes', interventions: 'interventions',
    performanceOverview: "Vue d'ensemble des performances",
    declareTitle: 'Déclarer une Panne', declareSubtitle: "Signalez un incident technique à l'équipe IT",
    submitPanne: 'Soumettre', reportAnother: 'Signaler une autre',
    submittedTitle: 'Rapport Soumis!', submittedSubtitle: "Votre rapport a été envoyé à l'équipe technique.",
    all: 'Tous', filterAll: 'Tous', active: 'Actif', inactive: 'Inactif',
    systemHealth: 'Santé Système', criticalActive: 'incidents critiques actifs',
    excellent: 'Excellent', fair: 'Acceptable', critical: 'Critique',
    activityFeed: 'Chronologie', activitySubtitle: "Historique chronologique des incidents",
    noActivity: 'Aucune activité enregistrée', searchPlaceholder: 'Rechercher par service, description ou technicien...',
    noResults: 'Aucun résultat', tryDifferent: 'Essayez un autre terme',
    noPannesFound: 'Aucune panne trouvée', addFirstPanne: 'Ajoutez votre première panne',
    noEquipment: 'Aucun équipement', addFirstEquipment: 'Ajoutez votre premier équipement',
    noUsers: 'Aucun utilisateur', addFirstUser: 'Ajoutez votre premier utilisateur',
    lowImpact: 'Impact faible', mediumImpact: 'Impact moyen', highImpact: 'Impact élevé',
    statusLabel: 'Statut', priorityLabel: 'Niveau de Priorité',
    thisWeek: 'cette semaine', vsLastWeek: 'vs semaine dernière',
    incidentsOpen: 'incidents ouverts', incidentsResolved: 'résolus cette semaine',
    needsAttention: 'nécessite attention',
    recentActivity: 'Pannes Récentes',
    recentActivitySub: '5 dernières pannes',
    timelineTitle: 'Chronologie',
    timelineSub: 'Historique complet avec détails',
    justNow: 'À l\'instant', today: 'Aujourd\'hui', yesterday: 'Hier',
    assignedTo: 'Assigné à', notAssigned: 'Non assigné',
  }
};

export default translations;